/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.Aluno;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class BoletimTest {

    @Test
    void situaçãoAprovada() {
        Aluno aluno = new Aluno("João", Arrays.asList(10.0, 10.0, 10.0));
        assertEquals("Aprovado", aluno.getSituacao());
    }

    @Test
    void situaçãoReprovada(){
        Aluno aluno = new Aluno("Pedro", Arrays.asList(2.0, 3.0, 2.3));
        assertEquals("Reprovado", aluno.getSituacao());
    }

    @Test
    void situaçãoRecuperação(){
        Aluno aluno = new Aluno("Lucas", Arrays.asList(5.0, 6.0, 4.5));
        assertEquals("Recuperação", aluno.getSituacao());
    }

    @Test
    void testarMediaExata(){
        Aluno aluno = new Aluno("Lorenzo", Arrays.asList(10.0, 6.0, 6.0));
        double media = aluno.calcularMedia();
        assertTrue(media >= 7);
    }
}

