name: Build

on:
  push:
    branches:
      - main

jobs:
  DigaOla:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Diga Olá
        uses: ./.github/actions/Diga-ola-action

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Permissão gradlew
        uses: ./.github/actions/Permissao-gradlew

      - name: Build com Gradle
        uses: ./.github/actions/Build-gradlew-action
